#dont forget to describe each role for what
default_roles:
# like cat but more fancy
  - bat
# like top but more fancy
  - bottom
  - discord
  - docker
  - doppler-cli
  - firefox
  - git
  - github-cli
  - go
  - kitty
  - lazygit
  - nvm
  - oh-my-zsh
  - postman
# like nvm but for python
  - pyenv
  - ripgrep
  - rust
  - spotify
  - visual-studio-code
  - keyd
  - sddm
  - zellij
  - nvim
  - wayland-Rofi
