- hosts: localhost
  connection: local

  vars:
    keyd_vars:
      PREFIX: "{{ ansible_user_dir }}/.local"
      CONFIG_DIR: "{{ ansible_user_dir }}/.config/keyd"
   
  pre_tasks:
    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always
    - name: Install yay
      ansible.builtin.import_tasks: pre_tasks/yay.yml
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: "{{ ansible_run_tags != ['all'] and ansible_run_tags or default_roles | difference(exclude_roles | default([])) }}"
      tags:
        - always

    - name: Display roles
      ansible.builtin.debug:
        var: run_roles
      tags:
        - always

    - name: Run system role
      ansible.builtin.include_role:
        apply:
          tags:
            - system
        name: system
      tags:
        - always

    - name: Run zsh role
      ansible.builtin.include_role:
        apply:
          tags:
            - zsh
        name: zsh
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always
    # - name: "Running Stow"