---

- name: "Install SDDM"
  ansible.builtin.pacman:
    name: 
      - sddm
    state: present
  become: true

- name: "Enable SDDM"
  ansible.builtin.systemd:
    name: sddm
    enabled: yes
    state: started
  become: true